export const mealDistribution = {
  breakfast: { label: "Café da manhã", share: 0.2 },
  morningSnack: { label: "Lanche da manhã", share: 0.1 },
  lunch: { label: "Almoço", share: 0.3 },
  afternoonSnack: { label: "Lanche da tarde", share: 0.1 },
  dinner: { label: "Jantar", share: 0.22 },
  supper: { label: "Ceia", share: 0.08 },
};

export const mealLibrary = {
  breakfast: [
    {
      id: "bf-1",
      name: "Iogurte com aveia, banana e chia",
      vegetarian: true,
      calories: 330,
      protein: 18,
      carbs: 45,
      fat: 9,
      ingredients: ["iogurte natural", "aveia", "banana", "chia"],
      tags: ["lactose"],
      items: [
        { food: "Iogurte natural", amount: 170, unit: "g" },
        { food: "Aveia", amount: 35, unit: "g" },
        { food: "Banana", amount: 1, unit: "un" },
        { food: "Chia", amount: 1, unit: "colher de sopa" },
      ],
    },
    {
      id: "bf-2",
      name: "Omelete com tapioca e mamão",
      vegetarian: true,
      calories: 360,
      protein: 22,
      carbs: 34,
      fat: 13,
      ingredients: ["ovos", "tapioca", "mamão", "queijo branco"],
      tags: ["ovo", "lactose"],
      items: [
        { food: "Ovos", amount: 2, unit: "un" },
        { food: "Tapioca", amount: 60, unit: "g" },
        { food: "Queijo branco", amount: 30, unit: "g" },
        { food: "Mamão", amount: 120, unit: "g" },
      ],
    },
    {
      id: "bf-3",
      name: "Sanduíche integral com frango e fruta",
      vegetarian: false,
      calories: 380,
      protein: 27,
      carbs: 38,
      fat: 10,
      ingredients: ["pão integral", "frango desfiado", "tomate", "maçã"],
      tags: ["gluten"],
      items: [
        { food: "Pão integral", amount: 2, unit: "fatia" },
        { food: "Frango desfiado", amount: 80, unit: "g" },
        { food: "Tomate", amount: 60, unit: "g" },
        { food: "Maçã", amount: 1, unit: "un" },
      ],
    },
    {
      id: "bf-4",
      name: "Vitamina de morango com pasta de amendoim",
      vegetarian: true,
      calories: 350,
      protein: 17,
      carbs: 36,
      fat: 14,
      ingredients: ["leite", "morango", "aveia", "pasta de amendoim"],
      tags: ["lactose", "amendoim"],
      items: [
        { food: "Leite", amount: 250, unit: "ml" },
        { food: "Morango", amount: 120, unit: "g" },
        { food: "Aveia", amount: 30, unit: "g" },
        { food: "Pasta de amendoim", amount: 20, unit: "g" },
      ],
    },
  ],
  morningSnack: [
    {
      id: "ms-1",
      name: "Mix de castanhas com pera",
      vegetarian: true,
      calories: 220,
      protein: 6,
      carbs: 20,
      fat: 12,
      ingredients: ["castanhas", "pera"],
      tags: ["oleaginosas"],
      items: [
        { food: "Castanhas", amount: 25, unit: "g" },
        { food: "Pera", amount: 1, unit: "un" },
      ],
    },
    {
      id: "ms-2",
      name: "Iogurte proteico com granola",
      vegetarian: true,
      calories: 210,
      protein: 15,
      carbs: 22,
      fat: 6,
      ingredients: ["iogurte proteico", "granola"],
      tags: ["lactose", "gluten"],
      items: [
        { food: "Iogurte proteico", amount: 160, unit: "g" },
        { food: "Granola", amount: 25, unit: "g" },
      ],
    },
    {
      id: "ms-3",
      name: "Hommus com cenoura e pepino",
      vegetarian: true,
      calories: 200,
      protein: 8,
      carbs: 18,
      fat: 10,
      ingredients: ["hommus", "cenoura", "pepino"],
      tags: ["grao de bico"],
      items: [
        { food: "Hommus", amount: 60, unit: "g" },
        { food: "Cenoura", amount: 80, unit: "g" },
        { food: "Pepino", amount: 80, unit: "g" },
      ],
    },
    {
      id: "ms-4",
      name: "Shake de banana com cacau",
      vegetarian: true,
      calories: 215,
      protein: 14,
      carbs: 28,
      fat: 5,
      ingredients: ["leite", "banana", "cacau", "aveia"],
      tags: ["lactose"],
      items: [
        { food: "Leite", amount: 220, unit: "ml" },
        { food: "Banana", amount: 1, unit: "un" },
        { food: "Aveia", amount: 20, unit: "g" },
        { food: "Cacau em pó", amount: 1, unit: "colher de sopa" },
      ],
    },
  ],
  lunch: [
    {
      id: "lu-1",
      name: "Frango grelhado com arroz, feijão e salada",
      vegetarian: false,
      calories: 590,
      protein: 42,
      carbs: 58,
      fat: 16,
      ingredients: ["frango", "arroz", "feijao", "alface", "tomate", "azeite"],
      tags: [],
      items: [
        { food: "Frango grelhado", amount: 140, unit: "g" },
        { food: "Arroz", amount: 130, unit: "g" },
        { food: "Feijão", amount: 100, unit: "g" },
        { food: "Salada verde", amount: 120, unit: "g" },
        { food: "Azeite", amount: 1, unit: "colher de sopa" },
      ],
    },
    {
      id: "lu-2",
      name: "Carne magra com purê de batata e legumes",
      vegetarian: false,
      calories: 610,
      protein: 38,
      carbs: 55,
      fat: 20,
      ingredients: ["patinho", "batata", "brocolis", "cenoura"],
      tags: [],
      items: [
        { food: "Carne magra", amount: 140, unit: "g" },
        { food: "Purê de batata", amount: 170, unit: "g" },
        { food: "Brócolis", amount: 80, unit: "g" },
        { food: "Cenoura", amount: 70, unit: "g" },
      ],
    },
    {
      id: "lu-3",
      name: "Bowl vegetariano com tofu, quinoa e legumes",
      vegetarian: true,
      calories: 560,
      protein: 28,
      carbs: 54,
      fat: 20,
      ingredients: ["tofu", "quinoa", "abobora", "brocolis", "grao de bico"],
      tags: ["soja", "grao de bico"],
      items: [
        { food: "Tofu grelhado", amount: 140, unit: "g" },
        { food: "Quinoa cozida", amount: 140, unit: "g" },
        { food: "Grão-de-bico", amount: 90, unit: "g" },
        { food: "Legumes assados", amount: 150, unit: "g" },
      ],
    },
    {
      id: "lu-4",
      name: "Salmão com batata-doce e vagem",
      vegetarian: false,
      calories: 600,
      protein: 40,
      carbs: 45,
      fat: 24,
      ingredients: ["salmao", "batata-doce", "vagem", "azeite"],
      tags: ["peixe"],
      items: [
        { food: "Salmão", amount: 150, unit: "g" },
        { food: "Batata-doce", amount: 180, unit: "g" },
        { food: "Vagem", amount: 100, unit: "g" },
        { food: "Azeite", amount: 1, unit: "colher de sopa" },
      ],
    },
  ],
  afternoonSnack: [
    {
      id: "as-1",
      name: "Pão integral com ricota e tomate",
      vegetarian: true,
      calories: 230,
      protein: 13,
      carbs: 24,
      fat: 8,
      ingredients: ["pão integral", "ricota", "tomate"],
      tags: ["gluten", "lactose"],
      items: [
        { food: "Pão integral", amount: 2, unit: "fatia" },
        { food: "Ricota", amount: 50, unit: "g" },
        { food: "Tomate", amount: 60, unit: "g" },
      ],
    },
    {
      id: "as-2",
      name: "Wrap de atum com folhas",
      vegetarian: false,
      calories: 245,
      protein: 18,
      carbs: 23,
      fat: 9,
      ingredients: ["wrap integral", "atum", "alface"],
      tags: ["gluten", "peixe"],
      items: [
        { food: "Wrap integral", amount: 1, unit: "un" },
        { food: "Atum", amount: 80, unit: "g" },
        { food: "Folhas verdes", amount: 50, unit: "g" },
      ],
    },
    {
      id: "as-3",
      name: "Fruta com iogurte e linhaça",
      vegetarian: true,
      calories: 215,
      protein: 11,
      carbs: 24,
      fat: 7,
      ingredients: ["iogurte natural", "fruta", "linhaca"],
      tags: ["lactose"],
      items: [
        { food: "Iogurte natural", amount: 170, unit: "g" },
        { food: "Fruta da estação", amount: 1, unit: "un" },
        { food: "Linhaça", amount: 1, unit: "colher de sopa" },
      ],
    },
    {
      id: "as-4",
      name: "Panqueca de banana com canela",
      vegetarian: true,
      calories: 240,
      protein: 10,
      carbs: 32,
      fat: 8,
      ingredients: ["banana", "ovo", "aveia", "canela"],
      tags: ["ovo"],
      items: [
        { food: "Banana", amount: 1, unit: "un" },
        { food: "Ovo", amount: 1, unit: "un" },
        { food: "Aveia", amount: 25, unit: "g" },
        { food: "Canela", amount: 1, unit: "colher de chá" },
      ],
    },
  ],
  dinner: [
    {
      id: "di-1",
      name: "Frango com legumes salteados e arroz integral",
      vegetarian: false,
      calories: 470,
      protein: 34,
      carbs: 42,
      fat: 14,
      ingredients: ["frango", "arroz integral", "abobrinha", "cenoura"],
      tags: [],
      items: [
        { food: "Frango grelhado", amount: 120, unit: "g" },
        { food: "Arroz integral", amount: 110, unit: "g" },
        { food: "Legumes salteados", amount: 160, unit: "g" },
      ],
    },
    {
      id: "di-2",
      name: "Sopa de lentilha com torradas integrais",
      vegetarian: true,
      calories: 430,
      protein: 22,
      carbs: 48,
      fat: 10,
      ingredients: ["lentilha", "cenoura", "cebola", "pão integral"],
      tags: ["gluten"],
      items: [
        { food: "Sopa de lentilha", amount: 320, unit: "ml" },
        { food: "Torradas integrais", amount: 3, unit: "un" },
      ],
    },
    {
      id: "di-3",
      name: "Omelete recheada com salada e mandioca",
      vegetarian: true,
      calories: 455,
      protein: 24,
      carbs: 35,
      fat: 18,
      ingredients: ["ovos", "queijo", "salada", "mandioca"],
      tags: ["ovo", "lactose"],
      items: [
        { food: "Omelete", amount: 2, unit: "un" },
        { food: "Queijo branco", amount: 30, unit: "g" },
        { food: "Salada", amount: 120, unit: "g" },
        { food: "Mandioca cozida", amount: 120, unit: "g" },
      ],
    },
    {
      id: "di-4",
      name: "Tofu acebolado com arroz e brócolis",
      vegetarian: true,
      calories: 445,
      protein: 23,
      carbs: 40,
      fat: 18,
      ingredients: ["tofu", "arroz", "brocolis", "cebola"],
      tags: ["soja"],
      items: [
        { food: "Tofu", amount: 140, unit: "g" },
        { food: "Arroz", amount: 120, unit: "g" },
        { food: "Brócolis", amount: 120, unit: "g" },
      ],
    },
  ],
  supper: [
    {
      id: "su-1",
      name: "Leite morno com cacau e banana",
      vegetarian: true,
      calories: 165,
      protein: 8,
      carbs: 22,
      fat: 5,
      ingredients: ["leite", "banana", "cacau"],
      tags: ["lactose"],
      items: [
        { food: "Leite", amount: 200, unit: "ml" },
        { food: "Banana", amount: 1, unit: "un" },
        { food: "Cacau", amount: 1, unit: "colher de chá" },
      ],
    },
    {
      id: "su-2",
      name: "Iogurte com kiwi",
      vegetarian: true,
      calories: 150,
      protein: 10,
      carbs: 18,
      fat: 4,
      ingredients: ["iogurte natural", "kiwi"],
      tags: ["lactose"],
      items: [
        { food: "Iogurte natural", amount: 160, unit: "g" },
        { food: "Kiwi", amount: 1, unit: "un" },
      ],
    },
    {
      id: "su-3",
      name: "Queijo cottage com canela e maçã",
      vegetarian: true,
      calories: 155,
      protein: 12,
      carbs: 16,
      fat: 4,
      ingredients: ["cottage", "maçã", "canela"],
      tags: ["lactose"],
      items: [
        { food: "Queijo cottage", amount: 90, unit: "g" },
        { food: "Maçã", amount: 1, unit: "un" },
        { food: "Canela", amount: 1, unit: "colher de chá" },
      ],
    },
    {
      id: "su-4",
      name: "Pudim de chia com manga",
      vegetarian: true,
      calories: 170,
      protein: 7,
      carbs: 19,
      fat: 7,
      ingredients: ["chia", "leite vegetal", "manga"],
      tags: [],
      items: [
        { food: "Chia", amount: 20, unit: "g" },
        { food: "Leite vegetal", amount: 160, unit: "ml" },
        { food: "Manga", amount: 80, unit: "g" },
      ],
    },
  ],
};
